### ISSUE TITLE
'node version 14 is not supported' - on lando start

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/docs#9]
```inn@finnibuntu:~/sites/l.localgov/docs$ lando start

  __  __        __     __        ___            _ __     __   __    ______
 / / / /__  ___/ /__ _/ /____   / _ |_  _____ _(_) /__ _/ /  / /__ / / / /
/ /_/ / _ \/ _  / _ `/ __/ -_) / __ | |/ / _ `/ / / _ `/ _ \/ / -_)_/_/_/ 
\____/ .__/\_,_/\_,_/\__/\__/ /_/ |_|___/\_,_/_/_/\_,_/_.__/_/\__(_|_|_)  
    /_/                                                                   

Updating helps us provide the best support and saves us tons of time

Use the link below to get the latest and greatest
https://github.com/lando/lando/releases/tag/v3.0.14

Lando is FREE and OPEN SOURCE software that relies on contributions from developers like you!
If you like Lando then help us spend more time making, updating and supporting it by contributing at the link below
https://github.com/sponsors/lando

If you would like to customize the behavior of this message then check out:
https://docs.lando.dev/config/releases.html
Let's get this party started! Starting app localgovdocs...
ERROR ==> node version 14 is not supported message=node version 14 is not supported, stack=Error: node version 14 is not supported
    at new LandoCompose (/snapshot/lando/build/cli/plugins/lando-core/compose/lando/builder.js)
    at new LandoAppserver (/snapshot/lando/build/cli/plugins/lando-core/types/appserver/builder.js)
    at new LandoNode (/snapshot/lando/build/cli/plugins/lando-services/services/node/builder.js)
    at /snapshot/lando/build/cli/plugins/lando-services/app.js
    at arrayEach (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:516:11)
    at Function.forEach (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:9368:14)
    at AsyncEvents.<anonymous> (/snapshot/lando/build/cli/plugins/lando-services/app.js)
    at AsyncEvents.handle (/snapshot/lando/build/cli/lib/events.js)
    at /snapshot/lando/build/cli/lib/events.js
From previous event:
    at AsyncEvents.emit (/snapshot/lando/build/cli/lib/events.js)
    at /snapshot/lando/build/cli/lib/app.js
From previous event:
    at App.init (/snapshot/lando/build/cli/lib/app.js)
    at initAndReport (/snapshot/lando/build/cli/lib/app.js)
    at App.start (/snapshot/lando/build/cli/lib/app.js)
    at Object.run (/snapshot/lando/build/cli/plugins/lando-core/tasks/start.js)
From previous event:
    at /snapshot/lando/build/cli/lib/cli.js
From previous event:
    at Object.handler (/snapshot/lando/build/cli/lib/cli.js)
    at Object.runCommand (/snapshot/lando/build/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.init (/snapshot/lando/build/cli/lib/cli.js)
    at Cli.run (/snapshot/lando/build/cli/lib/cli.js)
    at Object.<anonymous> (/snapshot/lando/build/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1324:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:993:10)
    at Module.load (internal/modules/cjs/loader.js:813:32)
    at Function.Module._load (internal/modules/cjs/loader.js:725:14)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1379:12)
    at internal/main/run_main_module.js:17:11, __stackCleaned__=true

██╗   ██╗██╗  ██╗     ██████╗ ██╗  ██╗██╗
██║   ██║██║  ██║    ██╔═══██╗██║  ██║██║
██║   ██║███████║    ██║   ██║███████║██║
██║   ██║██╔══██║    ██║   ██║██╔══██║╚═╝
╚██████╔╝██║  ██║    ╚██████╔╝██║  ██║██╗
 ╚═════╝ ╚═╝  ╚═╝     ╚═════╝ ╚═╝  ╚═╝╚═╝
                                         

An error occurred while starting up your app!
Here are a few things you can try to get back into a good state:

  ■ Try running lando rebuild
  ■ Try restarting in debug mode lando restart -vvv
  ■ Try checking the logs with lando logs

If those fail then consult the troubleshooting materials:

  ■ https://docs.lando.dev/help/logs.html
  ■ https://docs.lando.dev/help/updating.html

Or post your issue to Slack or GitHub

  ■ Slack - https://launchpass.com/devwithlando
  ■ GitHub - https://github.com/lando/lando/issues/new/choose

ERROR ==> node version 14 is not supported

**Comment by finnlewis** [comment]
Hey @paulpopus 

What do you make of this? Do I just need to update node or something?

**Comment by paulpopus** [comment]
@finnlewis Can you update your lando to the latest version? It might be that in yours it doesn't know there's an image for node 14

**Comment by paulpopus** [comment]
@finnlewis is this still an issue for you?

**Comment by finnlewis** [comment]
This is now working for my using lando v3.0.14

Thanks @paulpopus !
